### PR TITLE
Recommendations

### PR DESCRIPTION
**Pull request by asarazan**
- New "Who To Follow" screen

Due to rate limiting, I couldn't go with my original plan of a recursive search of your favorites' favorites (it was triggering 25 API calls per second).

I instead opted for a list of your favorite users, from which you can then drill down to see _that person's_ favorite users, etc.

We still need to get "Who I'm following" cached locally, as it's not stored on the user itself. This would allow the "Follow" buttons to be smarter. 

We might also probably have an avatar tap drill into the user profile screen?

### CODE REVIEW

**Comment by pawegio** [comment]
I'll have some merging with my local branch :)
I'm only missing small thing... `dropView()` in `TopUsersActivity`. Then I can merge it.

**Comment by asarazan** [comment]
Cool I'll take care of it tonight

**Comment by pawegio** [comment]
and I would maybe use `with(user)` in adapter `bind()` method:

```
fun bind(user: User, onClick: (User) -> Unit) {
    with(user) {
        itemView.name.text = name
        itemView.screen_name.text = screenName
        Glide.with(itemView.context).load(profileImageUrlHttps).into(itemView.image)
        itemView.setOnClickListener {
            onClick(this)
        }
        itemView.follow.setOnClickListener {
            KTwitterApiClient(Twitter.getSessionManager().activeSession).kTwitterApi.follow(id, true)
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribeOn(Schedulers.io())
                    .subscribe {
                        itemView.context.toast("Followed $screenName!")
                    }
        }
    }
}
```

**Comment by asarazan** [comment]
Ready to merge

**Pull request merged**
