### PR TITLE
Extension with optional arguments for tweets()

### PR DESCRIPTION
**Pull request by pawegio**
I've created extension for `tweets()` method to make call to `SearchService` more readable:

```
fun SearchService.tweets(s: String, geocode: Geocode? = null, s1: String? = null, s2: String? = null, s3: String? = null,
                         integer: Int? = null, s4: String? = null, aLong: Long? = null, aLong1: Long? = null,
                         aBoolean: Boolean? = null, callback: Callback<Search>) =
        tweets(s, geocode, s1, s2, s3, integer, s4, aLong, aLong1, aBoolean, callback)
```

### CODE REVIEW

**Comment by asarazan** [comment]
Lets create a new file/files, for twitter api extensions, as I doubt this will be the last one.

**Comment by asarazan** [comment]
I think we could also make the query optional, and just allow for named params all the way through? Seems reasonable to have no query but specify a user, for instance.

**Comment by pawegio** [comment]
Ok, agree that query should be optional & moving extensions.

**Comment by tudorluca** [comment]
You could also give some explicit names to the params.  See @GET(value="/1.1/search/tweets.json")
void tweets(@Query(value="q")
              java.lang.String query,
              @EncodedQuery(value="geocode")
              Geocode geocode,
              @Query(value="lang")
              java.lang.String lang,
              @Query(value="locale")
              java.lang.String locale,
              @Query(value="result_type")
              java.lang.String resultType,
              @Query(value="count")
              java.lang.Integer count,
              @Query(value="until")
              java.lang.String until,
              @Query(value="since_id")
              java.lang.Long sinceId,
              @Query(value="max_id")
              java.lang.Long maxId,
              @Query(value="include_entities")
              java.lang.Boolean includeEntities,
              Callback<Search> cb)

**Comment by pawegio** [comment]
done

**Pull request merged**
